version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: local-postgres
    environment:
      - POSTGRESQL_USERNAME=dev
      - POSTGRESQL_PASSWORD=devpass
      - POSTGRESQL_DATABASE=devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: {}