server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #active: native file , classPath
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/LeeJaeYoung0706/github-yml-study.git"
        #native:
          #search-locations: "file:///C://Users//qaz77//Downloads//config" ## 파일로 접근하기
          # 참고 https://docs.spring.io/spring-cloud-config/docs/current/reference/html/
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#          search-locations: "classpath:/config"