server:
  port: 9000
spring:
  application:
    name: cards
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    #    jdbc-url: jdbc:h2:tcp://localhost:9092/~/test
    username: sa
    password: ''
    jdbc-url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    #    properties:
    #      hibernate:
    #        show_sql: true
    show-sql: true
  h2:
    console:
      enabled: true

build:
  version: "3.0"

accounts:
  message: "마이크로서비스를 만들어 봅시다. PROD LOCAL API"
  contactDetails:
    name: "sidle ( Lee jae young )"
    email: "wodud@4019@gmail.com"
  onCallSupport:
    - 00000000
    - 00000001