

build:
  version: "3.0"

accounts:
  message: "마이크로서비스를 만들어 봅시다. LOCAL API"
  contactDetails:
    name: "sidle ( Lee jae young )"
    email: "wodud@4019@gmail.com"
  onCallSupport:
    - 00000000
    - 00000001